#include "Config.h"

double distance(double x1, double y1, double x2, double y2) {
    return sqrt(pow(x1 - x2, 2) + pow(y1 - y2, 2));
}

void generatePoints(double *points, int numPointsToCreate, Config config) {
    /// Generate Random Points
    for (int i = 0; i < numPointsToCreate; i++) {
        points[i * 2] = (random() / (double) RAND_MAX) * config.RAND_POINT_MAX;
        points[(i * 2) + 1] = (random() / (double) RAND_MAX) * config.RAND_POINT_MAX;

        if (config.__PRINT_RANDOM_POINTS__) {
            //* Print the points generated by the current process.
            //* Format: "identifier,i,x,y"
            printf("generated_points,%i,%lf,%lf\n", i, points[i * 2], points[(i * 2) + 1]);
        }
    }
}